// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZdKClxaRBJ4GtX1QgD9uuHNWWE8Dpbyw',
    appId: '1:671969268943:web:7e242663c27a2fe19253ba',
    messagingSenderId: '671969268943',
    projectId: 'basicappsdatabase',
    authDomain: 'basicappsdatabase.firebaseapp.com',
    storageBucket: 'basicappsdatabase.firebasestorage.app',
    measurementId: 'G-J7HEWMY98M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD33b0TYdkCvOtKsH6XmDh_Kn_S9pminuQ',
    appId: '1:671969268943:android:1eaab5cd42eb5c809253ba',
    messagingSenderId: '671969268943',
    projectId: 'basicappsdatabase',
    storageBucket: 'basicappsdatabase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm9drtdfZoAnWgEIrUVTizPa7M2S9jZA0',
    appId: '1:671969268943:ios:b75fcc312116ada49253ba',
    messagingSenderId: '671969268943',
    projectId: 'basicappsdatabase',
    storageBucket: 'basicappsdatabase.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm9drtdfZoAnWgEIrUVTizPa7M2S9jZA0',
    appId: '1:671969268943:ios:b75fcc312116ada49253ba',
    messagingSenderId: '671969268943',
    projectId: 'basicappsdatabase',
    storageBucket: 'basicappsdatabase.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZdKClxaRBJ4GtX1QgD9uuHNWWE8Dpbyw',
    appId: '1:671969268943:web:6ead01c4adb29f8d9253ba',
    messagingSenderId: '671969268943',
    projectId: 'basicappsdatabase',
    authDomain: 'basicappsdatabase.firebaseapp.com',
    storageBucket: 'basicappsdatabase.firebasestorage.app',
    measurementId: 'G-MSC6HYPMLF',
  );
}
